version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "brightpearl-data-integration-redshift-yeti-dev"
s3_bucket = "samclisourcebucket-redshift-prod-yeti-dev-cluster-dev"
s3_prefix = "brightpearl-data-integration"
region = "eu-west-2"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

